{
  imports = [
    ./hyprland
    ./waybar
    ./rofi
    ./mako.nix
    ./steam.nix
    ./chromium.nix
    ./udiskie.nix
    ./git.nix
    ./ssh.nix
    ./xdg.nix
    ./ydotool.nix
    ./sddm.nix
    ./terminal
    ./cliphist.nix
    ./vesktop.nix
    ./spotify.nix
    ./zathura.nix
    ./zen-browser.nix
  ];
}